<template>
  <div class="header-banner">
    <p class="header-text">
      🎉 The webpage is generated by EVM on EthStorage testnet.<br class="font-br"/>
      Get test tokens <a href="https://faucet.w3q.w3q-g.w3link.io/" target="_blank" class="w3q-link">here</a> and BUIDL now.
    </p>
  </div>
</template>

<style scoped>
.header-banner {
  width: 100%;
  background: #9671FF;
  min-height: 40px;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
}

.header-text {
  font-family: 'Avenir';
  font-style: normal;
  font-weight: 500;
  font-size: 18px;
  line-height: 140%;
  color: #FFFFFF;
  text-align: left;
}

a.w3q-link {
  text-decoration: none;
  border-bottom: 1px solid #FFFFFF;
}
a.w3q-link:link,
a.w3q-link:visited,
a.w3q-link:hover {
  color: #FFFFFF;
  background-color: transparent;
}
a.w3q-link:hover {
  filter: opacity(50%);
  background-color: transparent;
}

.font-br {
  display: none;
}

@media screen and (max-width: 500px) {
  .header-banner {
    align-items: flex-start;
    padding: 8px 5px;
  }

  .header-text {
    font-size: 10px;
    text-align: center;
  }

  .font-br {
    display: inherit;
  }
}
</style>
